### PR TITLE
Updated most offsets for new version

### PR DESCRIPTION
**Pull request by nightlark**
Okay, didn't mess up the PR this time. I updated most of the offsets for the latest patch, all of the major features work without crashing the client, and fog still works. I'm still not sure about the 0xNAN addresses, but the one thing I know needs updating is the debug pointer.

### CODE REVIEW

**Comment by karliky** [comment]
Hey @nightlark ! thank you for all the effort you put on this!

I'm going to close this issue as I had prepared some changes that I didn't commit because I found something strange in the latest patch.

They added a new set of instructions that change the look at vector so when you move the camera it flickrers the game screen. Don't you have problems in your machinima studio build? I'm curios to see you didn't reported anything.

Also, I think anet added a new security layer because when you move the camera far away from the player, the game crashes, is it a problem I just have or are you able to reproduce it?

I'll keep this open until you answer my but I won't merge it as I made some important changes that have conflicts with this PR, also I added a new method to resolve one of the three 0x00000NAN values, so now we only have 2 0x00000NAN values more to resolve 😄 I want to write a wiki page on how to update all the offsets....

Btw, I saw you've implemented the highlighting function, but it is not included in this PR, what happened?

**Comment by nightlark** [comment]
I only had crashes with the free camera and stopping animations, but updating the offsets fixed them. Just tried going to the opposite end of the map, no crash, and performance seemed okay (a couple spots of lag, probably not the flickering you're referring to?). Video: http://sendvid.com/q68qewnc

On a different system I had some interesting flicker stuff going on related to position the camera thought it should be at, but that only happened when I tried using the mouse to move the camera. I also can't reproduce that bug anymore.

I'm seeing if there is a better place to disable highlighting. The current patch works, but anything highlighted will remain highlighted after checking the box to disable highlighting; it's a minor issue (maybe some people would even find it useful), so with or without a fix I'll send another PR after merging it with your next update.

**Comment by nightlark** [comment]
@karliky Is the flickering something like in this ( http://sendvid.com/qsa8ykre ) video? I was able to reproduce the issue I had before - tilting the camera down slightly makes the view clip to below the water surface, in some other areas without the water it jumps to a view under the map.

**Comment by karliky** [comment]
I know a way to select npcs by setting the ID (int32 4 bytes) and that activates the high tough times so maybe setting it to 0 disables the highlight.....

I'm experiencing an issue with the latest patch, I saw your video and everything seems to work fine so I'm really surprised.

Can you move your player to Lion's arch? Then activate the freebie camera and move it far away (holding W pressed for 20 seconds should be enough) 

when I do this my game crashes :(

**Comment by karliky** [comment]
@nightlark yes, I know that problem, it also happens with the PVP spectate camera, when you introduce the lookat vector inside the water the game does a movement and applies the drops water effect in your screen.

No easy way to fix that...

**Comment by karliky** [comment]
If your game doesn't crashes when move the camera in Lion's arch, would you mind sharing with me your gw2.exe? Also your graphic settings would be good

**Comment by nightlark** [comment]
I wasn't so much worried about the water drops, but more how when the camera position is above the water, rotating the camera down shouldn't make it suddenly jump underwater, and then rotating back up makes it return to where it was before.

I went to the opposite end of the map in LA, and then flew up into the sky for another 20 seconds. I'm going to see if I can reproduce the crash you are getting.

**Comment by nightlark** [comment]
@karliky I figured out the crash. The new patch 3 has the same offset as patch 2 and is overwriting an instruction that should be left intact.

Also, the new patch 8 is identical to the old patch 3 (offset 0x00675623 is what the old patch 3 offset should be updated to).

**Comment by nightlark** [comment]
I've updated the files in my fork. Patches 6 & 7 were also identical.

Even after trying the latest upstream patch I didn't notice any flickering. Maybe ANet made a change that your graphics card doesn't like? I've uploaded a copy of my gw2.exe to http://www.filedropper.com/gw2_1

Graphics settings I'm using are:
Refresh Rate - Default
Frame Limiter - Unlimited
Antialiasing - FXAA
Reflections - All
Render Sampling - Native
With Ambient Occlusion, Best Texture Filtering, Depth Blur, Effect LOD, Light Adaptation, and Vertical Sync enabled, and all other settings on High.

**Comment by karliky** [comment]
I'm at the hospital right now in really bad condition, I've sent you an invitation as a collaborator so you can take care of the project, and commit directly or accept your own PRs, I won't be able to work on this while I'm sick and recovering at home, if you haven't receive the link send me an email to karliky@gmail.com

**Comment by karliky** [comment]
Thank you so much for your support

**Comment by karliky** [comment]
@nightlark not sure If you read my las 2 comments

**Comment by nightlark** [comment]
@karliky Yea, I've just been trying to figure out what to say as this news is rather sudden. I hope that your condition improves quickly and that you have a swift recovery.

**Comment by guillaumeguerin** [comment]
Hope you get well soon !

**Pull request merged**
